name = "fitness-backend"
main = "worker.js"
compatibility_date = "2025-09-23"
compatibility_flags = [ "nodejs_compat", "enable_nodejs_http_server_modules" ]

[triggers]
crons = ["6 17 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "fitness-db"
database_id = "755e2a29-59bb-49f6-aec5-3276d87c7b04"
migrations_dir = "migrations"

[vars]
NODE_ENV = "production"

# Note: DB_PASSWORD and JWT_SECRET should be created securely as Cloudflare secrets using:
# wrangler secret put DB_PASSWORD
# wrangler secret put JWT_SECRET
